# Generated by Django 2.2.2 on 2019-06-30 12:32

import apps.service.models
from django.db import migrations, models
import django.db.models.deletion
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('content', extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='产生时间')),
                ('look', models.IntegerField(null=True)),
                ('headImage', models.ImageField(upload_to=apps.service.models.FindPage.user_directory_path)),
            ],
            options={
                'verbose_name': '发现文章',
                'db_table': 'findpage',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='WealthBGModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.service.models.WealthBGModel.user_upload, verbose_name='天气背景图')),
                ('wealth', models.IntegerField(verbose_name='天气状况')),
            ],
            options={
                'verbose_name': '天气背景',
            },
        ),
        migrations.CreateModel(
            name='ShowPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, verbose_name='标题')),
                ('content', extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='产生时间')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'verbose_name': '晒一晒文章',
                'db_table': 'showpage',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=20, null=True, verbose_name='评论对象')),
                ('content', extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('time_l', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.ShowPage')),
            ],
            options={
                'verbose_name': '评论',
                'db_table': 'remark',
                'ordering': ['autor', 'page', 'time_l'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.service.models.Image.user_directory_path)),
                ('remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Remark')),
                ('showpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.ShowPage')),
            ],
            options={
                'verbose_name': '图片',
                'db_table': 'image',
            },
        ),
    ]
