# Generated by Django 2.2.2 on 2019-06-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='to',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='评论对象'),
        ),
    ]
