# Generated by Django 2.2.2 on 2019-07-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190630_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showpage',
            options={'ordering': ['-time'], 'verbose_name': '晒一晒文章'},
        ),
        migrations.AlterField(
            model_name='remark',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ShowPage'),
        ),
    ]
