# Generated by Django 2.2.2 on 2019-06-30 12:32

import apps.login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=2)),
                ('icon', models.ImageField(blank=True, upload_to=apps.login.models.User.user_directory_path)),
                ('registertime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'users',
            },
        ),
    ]
